alquiler/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.index, name="index"),

    # URLs para Usuario
    path('usuarios/', views.usuario_lista, name='usuario_lista'),
    path('usuarios/crear/', views.usuario_crear, name='usuario_crear'),
    path('usuarios/<int:usuario_id>/editar/', views.usuario_actualizar, name='usuario_actualizar'),
    path('usuarios/<int:usuario_id>/eliminar/', views.usuario_delete, name='usuario_delete'),

    # URLs para Perfil
    path('perfiles/', views.perfil_lista, name='perfil_lista'),
    path('perfiles/crear/', views.perfil_crear, name='perfil_crear'),
    path('perfiles/<int:perfil_id>/editar/', views.perfil_actualizar, name='perfil_actualizar'),
    path('perfiles/<int:perfil_id>/eliminar/', views.perfil_delete, name='perfil_delete'),

    # URLs para Categoria
    path('categorias/', views.categoria_lista, name='categoria_lista'),
    path('categorias/crear/', views.categoria_crear, name='categoria_crear'),
    path('categorias/<int:categoria_id>/editar/', views.categoria_actualizar, name='categoria_actualizar'),
    path('categorias/<categoria_id>/eliminar/', views.categoria_delete, name='categoria_delete'),

    # URLs para ServicioExtra
    path('serviciosextra/', views.servicioextra_lista, name='servicioextra_lista'),
    path('serviciosextra/crear/', views.servicioextra_crear, name='servicioextra_crear'),
    path('serviciosextra/<int:servicio_extra_id>/editar/', views.servicioextra_actualizar, name='servicioextra_actualizar'),
    path('serviciosextra/<int:servicio_extra_id>/eliminar/', views.servicioextra_delete, name='servicioextra_delete'),

    # URLs para Propiedad
    path('propiedades/', views.propiedad_lista, name='propiedad_lista'),
    path('propiedades/crear/', views.propiedad_crear, name='propiedad_crear'),
    path('propiedades/<int:propiedad_id>/editar/', views.propiedad_actualizar, name='propiedad_actualizar'),
    path('propiedades/<int:propiedad_id>/eliminar/', views.propiedad_delete, name='propiedad_delete'),

    # URLs para Prioridad
    path('prioridades/', views.prioridad_lista, name='prioridad_lista'),
    path('prioridades/crear/', views.prioridad_crear, name='prioridad_crear'),
    path('prioridades/<int:prioridad_id>/editar/', views.prioridad_actualizar, name='prioridad_actualizar'),
    path('prioridades/<int:prioridad_id>/eliminar/', views.prioridad_delete, name='prioridad_delete'),

    path('usuarios/<str:email>/', views.usuario_detalle, name='usuario_detalle'),  # OneToOne
    path('propiedades/', views.lista_propiedades, name='lista_propiedades'),  # ManyToMany
    path('categorias/<int:id>/', views.detalle_categoria, name='detalle_categoria'),  # QuerySet con parámetros
    path('propiedad/reservas/<int:propiedad_id>/', views.reservas_propiedad, name='reservas_propiedad'),  # Filtro ManyToOne
    path('comentarios/propiedad/<int:propiedad_id>/', views.comentarios_propiedad, name='comentarios_propiedad'),  # Reverse
    path('reservas/filtro/', views.filtrar_reservas, name='filtrar_reservas'),  # Filtros con AND y OR
    path('categorias/none/', views.categorias_sin_propiedades, name='categorias_sin_propiedades'),  # None intermedio
    path('propiedades/precios/', views.propiedad_precio_agregado, name='propiedad_precio_agregado'),  # Aggregate
    path('usuarios/recientes/', views.usuarios_recientes, name='usuarios_recientes'),# OrderBy y limit
    path('error/404/', views.error_404, name='error_404'),  # Error personalizado
    path('error/404/', views.error_404, name='error_404'),  # Error personalizado
    path('error/404/', views.error_404, name='error_404'),  # Error personalizado
    path('error/404/', views.error_404, name='error_404'),  # Error personalizado

    #Registrar 
    path('registrar', views.registrar_usuario, name='registrar_usuario'),

    #Logout
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("alquiler.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

alquiler/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


class UsuarioLogin (AbstractUser):
    ADMINISTRADOR = 1 
    ANFRITION = 2
    USUARIO = 3     
    ROLES = (
        (ADMINISTRADOR, 'administrador'),
        (ANFRITION, 'anfrition'),
        (USUARIO, 'usuario'),
        )

    rol = models.PositiveSmallIntegerField(
        choices=ROLES,default=3
    )

class Usuario(models.Model): 
    usuario = models.OneToOneField(UsuarioLogin, on_delete=models.CASCADE)   

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    telefono = models.CharField(max_length=20, blank=True)
    fecha_registro = models.DateTimeField(db_column="fecha", null=False, default=datetime.now)



class Perfil(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='perfil')
    genero = models.CharField(max_length=10)
    edad = models.PositiveIntegerField()
    ubicacion = models.TextField()
    biografia = models.TextField()


class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    premiun = models.BooleanField()
    principal = models.BooleanField()


class ServicioExtra(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.IntegerField()
    disponible = models.BooleanField()

class Propiedad(models.Model):
    titulo = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    precio_por_noche = models.IntegerField()
    max_usuarios = models.PositiveIntegerField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='propiedades')
    categoria = models.ManyToManyField(Categoria, through='CategoriaPrincipal', related_name='propiedades')
    servicios_extra = models.ManyToManyField(ServicioExtra, related_name='propiedades')

class Prioridad(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=255, null=False, default='valor_por_defecto')

    premiun = models.BooleanField()
    numero = models.IntegerField()
    propiedades = models.ManyToManyField(Propiedad, related_name='prioridades')

class Pago(models.Model):
    total = models.FloatField(help_text="Total del pago")
    fecha_pago = models.DateTimeField()
    metodo_pago = models.CharField(max_length=50)
    cod_transaccion = models.CharField(max_length=100)


class Reserva(models.Model):
    fecha_inicio = models.DateField()
    fecha_fin = models.DateTimeField()
    total = models.FloatField()
    estado = models.CharField(max_length=20)
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name='reservas')
    pago = models.OneToOneField(Pago, on_delete=models.CASCADE, related_name='reserva_pago', blank=True)  # Aquí 'default=1' es un ejemplo
    perfil = models.OneToOneField(Perfil, on_delete=models.CASCADE, related_name='reserva')


class Comentario(models.Model):
    contenido = models.TextField()
    fecha_comentario = models.DateTimeField()
    valoracion = models.IntegerField()
    anonimo = models.BooleanField()
    propiedad = models.ForeignKey('Propiedad', on_delete=models.CASCADE, related_name='comentarios')


class CategoriaPrincipal(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='categoria_principal')
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name='categoria_principal')

    
class Anfrition(models.Model):
    usuario = models.OneToOneField(UsuarioLogin , on_delete=models.CASCADE)
     
    telefono = models.CharField(max_length=20, blank=True)
    

alquiler/forms.py
from django import forms
from .models import *  
from django.contrib.auth.forms import UserCreationForm

# Formulario para Usuario
class UsuarioForm(forms.ModelForm):
    username = forms.CharField(
        max_length=150, 
        required=True, 
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Nombre de Usuario"
    )
    password = forms.CharField(
        required=True, 
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Contraseña"
    )

    class Meta:
        model = Usuario
        fields = ['email', 'telefono', 'fecha_registro']  # Ya no es necesario incluir 'nombre'
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_registro': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        }

    # Validacion para el  email, verifica que no exista en la base de datos 
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo ya está registrado")  
        return email

    # Validacion personalizada para el campo "nombre", verifica que no exista en la base de datos 
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if Usuario.objects.filter(nombre=nombre).exists():  
            raise forms.ValidationError("Este nombre ya está registrado")
        return nombre


# Formulario para Perfil
class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['genero', 'edad', 'ubicacion', 'biografia']
        widgets = {
            'genero': forms.Select(choices=[('M', 'Masculino'), ('F', 'Femenino')], attrs={'class': 'form-control'}),
            'edad': forms.NumberInput(attrs={'class': 'form-control'}),
            'ubicacion': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'biografia': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }

    # Validacion para edad,  pongo una edad minima y otra maxima, para crear el perfil 
    def clean_edad(self):
        edad = self.cleaned_data.get('edad')
        if edad is not None:
            if edad < 18:  
                raise forms.ValidationError("La edad debe ser mayor  a 18 años")
            if edad > 100: 
                raise forms.ValidationError("La edad no puede ser mayor a 100 años")
        return edad

    # Validacion para asegurar una longitud mínima en la biografía
    def clean_biografia(self):
        biografia = self.cleaned_data.get('biografia')
        if len(biografia) < 50:  
            raise forms.ValidationError("La biografía debe tener al menos 50 caracteres")
        return biografia


# Formulario para Categoria
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion', 'premiun', 'principal']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'premiun': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'principal': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    # Validacion para asegurar que el nombre no este en la base de datos 
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if Categoria.objects.filter(nombre=nombre).exists():
            raise forms.ValidationError("Este nombre ya está registrado")
        return nombre

    # Validación para la descripcion, minimo 30 caracteress
    def clean_descripcion(self):
        descripcion = self.cleaned_data.get('descripcion')
        if len(descripcion) < 30:
            raise forms.ValidationError("La descripción debe tener al menos 30 caracteres")
        return descripcion


# Formulario para ServicioExtra
class ServicioExtraForm(forms.ModelForm):
    class Meta:
        model = ServicioExtra
        fields = ['nombre', 'descripcion', 'precio', 'disponible']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'disponible': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    # Validacioan para asegurar que el precio sea mayor a 10
    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if precio is not None and precio <= 10:
            raise forms.ValidationError("El precio debe ser mayor a 10")
        return precio


# Formulario para Propiedad
class PropiedadForm(forms.ModelForm):
    class Meta:
        model = Propiedad
        fields = ['titulo', 'direccion', 'precio_por_noche', 'max_usuarios', 'usuario', 'categoria']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'precio_por_noche': forms.NumberInput(attrs={'class': 'form-control'}),
            'max_usuarios': forms.NumberInput(attrs={'class': 'form-control'}),
            'usuario': forms.Select(attrs={'class': 'form-control'}),
            'categoria': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    # Validacion para asegurar que el precio no sea negativo 
    def clean_precio_por_noche(self):
        precio = self.cleaned_data.get('precio_por_noche')
        if precio is not None and precio <= 0:
            raise forms.ValidationError("El precio por noche debe ser mayor a 0")
        return precio

    # Validacion para asegurar el minimo y max de usuarios 
    def clean_max_usuarios(self):
        max_usuarios = self.cleaned_data.get('max_usuarios')
        if max_usuarios is not None:
            if max_usuarios < 1:
                raise forms.ValidationError("El número máximo de usuarios debe ser al menos 1")
            if max_usuarios > 20:
                raise forms.ValidationError("El número máximo de usuarios no puede exceder 20")
        return max_usuarios


# Formulario para Prioridad
class PrioridadForm(forms.ModelForm):
    class Meta:
        model = Prioridad
        fields = ['nombre', 'descripcion', 'premiun', 'numero']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'premiun': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'numero': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    # Validacion para comprobar que el nombre sea unico
    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if Prioridad.objects.filter(nombre=nombre).exists():
            raise forms.ValidationError("El nombre ya está registrado.")
        return nombre

    # Validacion para que el numero sea entre el 1 y el 10
    def clean_numero(self):
        numero = self.cleaned_data.get('numero')
        if numero is not None:
            if numero < 1 or numero > 10:
                raise forms.ValidationError("El número debe estar entre 1 y 10")
        return numero



#Formulario de registro 
class RegistroForm (UserCreationForm):
    ROLES = (
                (UsuarioLogin.ANFRITION, 'anfrition'),
                (UsuarioLogin.USUARIO, 'usuario'),
    )
    
    rol =   forms.ChoiceField(choices=ROLES)
    
    class Meta:
        model = UsuarioLogin
        fields = ['username' , 'email', 'password1', 'password2', 'rol']

alquiler/templates/Usuario/usuario_actualizar.html
{% extends 'principal.html' %}

{% block contenido %}
    {% if user.is_authenticated %}
        {% if perms.alquiler.change_usuario %}
            <h1>Actualizar Usuario</h1>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Actualizar</button>
            </form>
        {% else %}
            <p>No tienes permiso para actualizar el usuario.</p>
        {% endif %}
    {% else %}
        <p>No estás logueado. Por favor, <a href="{% url 'login' %}">inicia sesión</a> para actualizar el usuario.</p>
    {% endif %}
{% endblock %}

alquiler/templates/Usuario/usuario_confirm.html
{% extends "principal.html" %}

{% block contenido %}
    {% if user.is_authenticated %}
        {% if perms.alquiler.delete_usuario %}
            <h1>Usuario Eliminado</h1>
            <p>El usuario ha sido eliminado con éxito.</p>
            <a href="{% url 'usuario_lista' %}">Volver a la lista de usuarios</a>
        {% else %}
            <p>No tienes permiso para eliminar usuarios.</p>
        {% endif %}
    {% else %}
        <p>No estás logueado. Por favor, <a href="{% url 'login' %}">inicia sesión</a> para continuar.</p>
    {% endif %}
{% endblock contenido %}

alquiler/templates/Usuario/usuario_crear.html
{% extends 'principal.html' %}

{% block contenido %}
    {% if user.is_authenticated %}
        {% if perms.alquiler.add_usuario %}
            <h1>Crear Usuario</h1>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Crear</button>
            </form>
        {% else %}
            <p>No tienes permiso para crear usuarios.</p>
        {% endif %}
    {% else %}
        <p>No estás logueado. Por favor, <a href="{% url 'login' %}">inicia sesión</a> para continuar.</p>
    {% endif %}
{% endblock %}

alquiler/templates/Usuario/usuario_eliminar.html
{% extends "principal.html" %}

{% block contenido %}
    {% if user.is_authenticated %}
        {% if perms.alquiler.delete_usuario %}
            <h1>Eliminar Usuario</h1>
            <form method="post">
                {% csrf_token %}
                <p>¿Estás seguro de que deseas eliminar al usuario {{ usuario.nombre }}?</p>
                <button type="submit">Sí, eliminar</button>
                <a href="{% url 'usuario_lista' %}">Cancelar</a>
            </form>
        {% else %}
            <p>No tienes permiso para eliminar usuarios.</p>
        {% endif %}
    {% else %}
        <p>No estás logueado. Por favor, <a href="{% url 'login' %}">inicia sesión</a> para continuar.</p>
    {% endif %}
{% endblock contenido %}

alquiler/templates/Usuario/usuario_lista.html
{% extends 'principal.html' %}

{% block contenido %}
    {% if user.is_authenticated %}
        {% if perms.alquiler.view_usuario %}
            <h1>Lista de Usuarios</h1>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Telefono</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.id }}</td>
                        <td>{{ usuario.nombre }}</td>
                        <td>{{ usuario.telefono }}</td>
                        <td>{{ usuario.email }}</td>
                        <td>
                            {% if perms.alquiler.change_usuario %}
                                <a href="{% url 'usuario_actualizar' usuario.id %}">Actualizar</a>
                            {% endif %}
                            {% if perms.alquiler.delete_usuario %}
                                <a href="{% url 'usuario_delete' usuario.id %}">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if perms.alquiler.add_usuario %}
                <a href="{% url 'usuario_crear' %}">Crear nuevo usuario</a>
            {% endif %}
        {% else %}
            <p>No tienes permiso para ver la lista de usuarios.</p>
        {% endif %}
    {% else %}
        <p>No estás logueado. Por favor, <a href="{% url 'login' %}">inicia sesión</a> para continuar.</p>
    {% endif %}
{% endblock %}